require "prototypes.subgroups"
require "prototypes.category.recipe"
require "prototypes.category.module"

require "prototypes.base.base"
require "prototypes.raw-resources.raw-resources"
require "prototypes.chemistry.chemistry"
require "prototypes.gardening.gardening"
require "prototypes.husbandry.husbandry"
require "prototypes.electronics.electronics"
