require "__rufmorio-lib__.lib.metas.item"
require "__rufmorio-lib__.lib.metas.recipe"
require "__rufmorio-lib__.lib.metas.technology"
require "__rufmorio-lib__.lib.metas.fluid"
require "__rufmorio-lib__.lib.metas.entity"

require "base-updates"

require "prototypes.subgroups"

require "prototypes.category.recipe"

require "prototypes.item.ore.raw.trimidium"
require "prototypes.item.ore.raw.olvalchite"
-- require "prototypes.item.ore.raw.myridium"
-- require "prototypes.item.ore.raw.plenoxite"
-- require "prototypes.item.ore.raw.utritium"
-- require "prototypes.item.ore.raw.halocite"
-- require "prototypes.item.ore.raw.xenoxium"

require "prototypes.item.plate.trimidium"
require "prototypes.item.plate.olvalchite"

require "prototypes.item.trimidium-stick"
require "prototypes.item.trimidium-stilt"
require "prototypes.item.trimidium-gear"
require "prototypes.item.trimidium-drill-base"
require "prototypes.item.olvalchite-drill-connector"
require "prototypes.item.trimidium-screw"
require "prototypes.item.trimidium-bolt"
require "prototypes.item.drill-bit"
require "prototypes.item.crafting.burner-drill"

require "prototypes.entity.crafting.burner-drill"

require "prototypes.recipe.mining.trimidium"
require "prototypes.recipe.mining.olvalchite"
require "prototypes.recipe.mining.stone"
-- require "prototypes.recipe.mining.myridium"
-- require "prototypes.recipe.mining.plenoxite"
-- require "prototypes.recipe.mining.utritium"
-- require "prototypes.recipe.mining.halocite"
-- require "prototypes.recipe.mining.xenoxium"
require "prototypes.recipe.smelting.trimidium-plate"
require "prototypes.recipe.smelting.olvalchite-plate"
require "prototypes.recipe.intermediate.trimidium-stick"
require "prototypes.recipe.intermediate.drill-bit"
require "prototypes.recipe.intermediate.trimidium-stilt"
require "prototypes.recipe.intermediate.trimidium-gear"
require "prototypes.recipe.intermediate.trimidium-drill-base"
require "prototypes.recipe.intermediate.olvalchite-drill-connector"
require "prototypes.recipe.intermediate.trimidium-screw-1"
require "prototypes.recipe.intermediate.trimidium-bolt-1"
require "prototypes.recipe.burner-drill"