require "prototypes.subgroups"
-- require "prototypes.autoplace-controls"

-- require "prototypes.resource.trimidium-ore"

require "prototypes.category.recipe"

require "prototypes.item.ore.raw.trimidium"
require "prototypes.item.ore.raw.olvalchite"
-- require "prototypes.item.ore.raw.myridium"
-- require "prototypes.item.ore.raw.plenoxite"
-- require "prototypes.item.ore.raw.utritium"
-- require "prototypes.item.ore.raw.halocite"
-- require "prototypes.item.ore.raw.xenoxium"

require "prototypes.item.plate.trimidium"
require "prototypes.item.plate.olvalchite"

require "prototypes.item.intermediate.trimidium-stick"
require "prototypes.item.intermediate.trimidium-stilt"
require "prototypes.item.intermediate.trimidium-gear"
require "prototypes.item.intermediate.trimidium-drill-base"
require "prototypes.item.intermediate.olvalchite-drill-connector"
require "prototypes.item.intermediate.trimidium-screw"
require "prototypes.item.intermediate.trimidium-bolt"
require "prototypes.item.drill-bit"

require "prototypes.item.crafting.burner-drill"
require "prototypes.item.crafting.atmospheric-condenser"

require "prototypes.fluid.gaseous-oxygen"

require "prototypes.entity.crafting.burner-drill"
require "prototypes.entity.crafting.atmospheric-condenser"

require "prototypes.recipe.mining.trimidium"
require "prototypes.recipe.mining.olvalchite"
require "prototypes.recipe.mining.stone"
-- require "prototypes.recipe.mining.myridium"
-- require "prototypes.recipe.mining.plenoxite"
-- require "prototypes.recipe.mining.utritium"
-- require "prototypes.recipe.mining.halocite"
-- require "prototypes.recipe.mining.xenoxium"
require "prototypes.recipe.smelting.trimidium-plate"
require "prototypes.recipe.smelting.olvalchite-plate"
require "prototypes.recipe.intermediate.trimidium-stick"
require "prototypes.recipe.intermediate.drill-bit"
require "prototypes.recipe.intermediate.trimidium-stilt"
require "prototypes.recipe.intermediate.trimidium-gear"
require "prototypes.recipe.intermediate.trimidium-drill-base"
require "prototypes.recipe.intermediate.olvalchite-drill-connector"
require "prototypes.recipe.intermediate.trimidium-screw-1"
require "prototypes.recipe.intermediate.trimidium-bolt-1"
require "prototypes.recipe.burner-drill"
require "prototypes.recipe.condensing.oxygen"