require "entity.lab.burner-lab"

require "item.intermediate.olvalchite-drill-connector"
require "item.intermediate.trimidium-bolt"
require "item.intermediate.trimidium-drill-base"
require "item.intermediate.trimidium-gear"
require "item.intermediate.trimidium-screw"
require "item.intermediate.trimidium-stick"
require "item.intermediate.trimidium-stilt"
require "item.tool.basic-science-pack"
require "item.burner-lab"

require "recipe.intermediate.olvalchite-drill-connector"
require "recipe.intermediate.trimidium-bolt-1"
require "recipe.intermediate.trimidium-drill-base"
require "recipe.intermediate.trimidium-gear"
require "recipe.intermediate.trimidium-screw-1"
require "recipe.intermediate.trimidium-stick"
require "recipe.intermediate.trimidium-stilt"
require "recipe.lab.burner-lab"
require "recipe.tool.basic-science-pack"

require "technology.electric-lab"
require "technology.electricity"
require "technology.solder"