require "entity.burner-drill"
require "entity.ore-washer"

require "item.drill-bit"
require "item.ore.raw.halocite"
require "item.ore.raw.myridium"
require "item.ore.raw.olvalchite"
require "item.ore.raw.plenoxite"
require "item.ore.raw.trimidium"
require "item.ore.raw.utritium"
require "item.ore.raw.xenoxium"
require "item.ore.washed.trimidium"
require "item.plate.myridium"
require "item.plate.olvalchite"
require "item.plate.trimidium"
require "item.production-machine.burner-drill"
require "item.production-machine.ore-washer"

require "recipe.mining.myridium"
require "recipe.mining.olvalchite"
require "recipe.mining.stone"
require "recipe.mining.trimidium"
require "recipe.production-machine.burner-drill"
require "recipe.production-machine.ore-washer"
require "recipe.smelting.myridium-plate"
require "recipe.smelting.olvalchite-plate"
require "recipe.smelting.trimidium-plate"
require "recipe.washing.trimidium"
require "recipe.drill-bit"

require "technology.alloys"
require "technology.casting"
require "technology.smelting"
require "technology.trimidium-processing-1"